COUNTRY_CHOICES = [
    ("United States", "United States"),
    ("Canada", "Canada"),
    ("United Kingdom", "United Kingdom"),
    ("Australia", "Australia"),
    ("Germany", "Germany"),
    ("France", "France"),
    ("Italy", "Italy"),
    ("Spain", "Spain"),
    ("Netherlands", "Netherlands"),
    ("Sweden", "Sweden"),
    ("Norway", "Norway"),
    ("Denmark", "Denmark"),
    ("Finland", "Finland"),
    ("Switzerland", "Switzerland"),
    ("Belgium", "Belgium"),
    ("Ireland", "Ireland"),
    ("Poland", "Poland"),
    ("Portugal", "Portugal"),
    ("Russia", "Russia"),
    ("China", "China"),
    ("Japan", "Japan"),
    ("South Korea", "South Korea"),
    ("India", "India"),
    ("Pakistan", "Pakistan"),
    ("UAE", "UAE"),
    ("Saudi Arabia", "Saudi Arabia"),
    ("Qatar", "Qatar"),
    ("Turkey", "Turkey"),
    ("Brazil", "Brazil"),
    ("Argentina", "Argentina"),
    ("Mexico", "Mexico"),
    ("South Africa", "South Africa"),
    ("Egypt", "Egypt"),
    ("Nigeria", "Nigeria"),
    ("Kenya", "Kenya"),
    ("New Zealand", "New Zealand"),
    ("Malaysia", "Malaysia"),
    ("Singapore", "Singapore"),
    ("Thailand", "Thailand"),
    ("Vietnam", "Vietnam"),
    ("Philippines", "Philippines"),
    ("Bangladesh", "Bangladesh"),
    ("Sri Lanka", "Sri Lanka"),
    ("Iran", "Iran"),
    ("Iraq", "Iraq"),
    ("Indonesia", "Indonesia"),
    ("Israel", "Israel"),
    ("Greece", "Greece"),
    ("Austria", "Austria"),
    ("Hungary", "Hungary"),
]
