# Generated by Django 5.2.8 on 2026-04-10 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("batting", "Batting"),
                            ("bowling", "Bowling"),
                            ("fitness", "Fitness"),
                        ],
                        max_length=20,
                    ),
                ),
                ("improvement_area", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("batter", "Batter"),
                            ("bowler", "Bowler"),
                            ("allrounder", "All-Rounder"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[("match", "Match"), ("practice", "Practice")],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("opponent", models.CharField(blank=True, max_length=100)),
                ("venue", models.CharField(blank=True, max_length=100)),
                ("result", models.CharField(blank=True, max_length=20)),
                ("practice_type", models.CharField(blank=True, max_length=100)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("focus_area", models.CharField(blank=True, max_length=100)),
                ("runs", models.IntegerField(blank=True, null=True)),
                ("balls", models.IntegerField(blank=True, null=True)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("dismissal_type", models.CharField(blank=True, max_length=50)),
                ("short_ball_success", models.FloatField(blank=True, null=True)),
                ("cover_drive_success", models.FloatField(blank=True, null=True)),
                ("overs", models.FloatField(blank=True, null=True)),
                ("runs_conceded", models.IntegerField(blank=True, null=True)),
                ("wickets", models.IntegerField(blank=True, null=True)),
                ("yorker_accuracy", models.FloatField(blank=True, null=True)),
                ("line_length_accuracy", models.FloatField(blank=True, null=True)),
                ("catches", models.IntegerField(default=0)),
                ("run_outs", models.IntegerField(default=0)),
                ("ai_feedback", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="videos/")),
                ("video_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="performance.performance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
