# Generated by Codex on 2026-04-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="performance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="performance.performance",
            ),
        ),
    ]
